server.port=8207
spring.application.name=service-orders
spring.profiles.active=dev

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://172.1.2.50:3306/yygh_order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.data.mongodb.uri=mongodb://172.1.2.50:27017/test

spring.cloud.nacos.discovery.server-addr=172.1.2.50:8848

spring.rabbitmq.host=172.1.2.50
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.data.redis.host=172.1.2.50
spring.data.redis.port=6379
spring.data.redis.database= 0
spring.data.redis.timeout=1800000
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-wait=-1

spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=0

weixin.pay.appid=wx74862e0dfcf69954
weixin.pay.partner=1558950191
weixin.pay.partnerkey=T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
weixin.cert=C:\\apiclient_cert.p12

mybatis-plus.mapper-locations=classpath:com/atguigu/yygh/orders/mapper/xml/*.xml

spring.cloud.sentinel.transport.dashboard=172.1.2.50:8858
spring.cloud.sentinel.transport.port=8858

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId:-NO-TRACE}] %logger{50} - %msg%n
